Stock-App/config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  #get 'welcome/index'

  root 'welcome#index'
  get 'welcome/about'

  post "/" => 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Stock-App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Stock-App/app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
end

Stock-App/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :stocks
end

Stock-App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Stock-App/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice "Not Authorized to edit this stock" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

Stock-App/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if params[:ticker] == ""
      @nothing = "Please enter a ticker symbol"
    elsif params[:ticker]
       @stock = StockQuote::Stock.quote(params[:ticker]) 
       if !@stock
          @error = "That stock symbol doesn't exist. Please enter a valid symbol."
       end
    end
    
  end

  def about
  end

end

Stock-App/app/helpers/application_helper.rb
module ApplicationHelper
end

Stock-App/app/helpers/stocks_helper.rb
module StocksHelper
end

Stock-App/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Stock-App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Stock App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style='background-image: linear-gradient(111deg, #30b2da, #47ceba, 53%, #82c55b)';>

   <%= render 'welcome/navbar' %>
      <div class="container">
      <%= render 'welcome/flash' %>

        <br>
        <%= yield %>
      </div>
      <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <%= render 'welcome/footer' %>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

Stock-App/app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Stock-App/app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

Stock-App/app/views/stocks/index.html.erb
<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.ticker %></td>
        <td><%= stock.user_id %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

Stock-App/app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

Stock-App/app/views/stocks/show.html.erb
<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<p>
  <strong>User:</strong>
  <%= @stock.user_id %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

Stock-App/app/views/welcome/_flash.html.erb
<br/>

<% flash.each do |name, msg| %>

    <div class="alert alert-warning alert-dismissable" role="alert">
        <button class="close" data-dismiss="alert">
            <small><sup>x</sup></small>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

Stock-App/app/views/welcome/_footer.html.erb
<br><br><br><br><br><br>


<center>Copyright (c) 2019 Joshua Harnois</center>

Stock-App/app/views/welcome/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark", style='background-image: linear-gradient(111deg, #30b2da, #47ceba, 53%, #82c55b)';>
<%= link_to 'Stock App', root_path, class: "navbar-brand" %> 
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
      <%= link_to 'About', welcome_about_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>

        <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to 'Log Out', destroy_user_session_path, method: :delete,  class: "nav-link" %>
        </li>

        <% else %>

        <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
        </li>

        

        <li class="nav-item">
            <%= link_to 'Show Stocks', stocks_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to 'Add Stock', new_stock_path, class: "nav-link" %>
        </li>

<% end %>
   
     
    </ul>
    
  </div>
</nav>

Stock-App/app/views/welcome/about.html.erb
<div class="col-md-6 offset-md-3">
    <div class='jumbotron'>
        <h1>About</h1>
        <p>This is a web application that keeps track of a stock portfolio for an asset management company.</p>
    </div>
</div>

Stock-App/app/views/welcome/index.html.erb
<h1>Stock App</h1>
<p>Stock Market App</p>


<%= form_tag root_path, :method => 'POST' do %>
    <%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
    <%= submit_tag 'Lookup' %>
<% end %>

 <% StockQuote::Stock.new(api_key: 'pk_a712cd430b984f7fbbab3ccd01047115') %>

<br/>

<% if @stock %>
    
    <%= @stock.company_name %><br/>
    $<%= @stock.latest_price %><br/>
<% elsif @nothing %>
    <%= @nothing %>
<% end %>

<% if @error %>
    <%= @error %>
<% end %>